name: 'linksafe-action'
branding:
    icon: 'check'
    color: 'purple'

description: 'Check all links and ensure they are not broken'
inputs:
  dirs:
    description: 'File path for each directory to scan'
    required: false
    default: '.'
  whitelist_links:  # id of input
    description: 'Links to ignore even if they"re broken'
    required: false
    default: 'None'
  whitelist_files:
    description: 'Files that will not be scanned'
    required: false
    
  verbose:
    description: 'Whether output should be verbose or not'
    required: false
    default: false
#outputs:
#  link-status: # id of output
#    description: 'Whether or not the check passed'
runs:
  using: 'composite'
  steps:
  - name: setup python
    uses: actions/setup-python@v3
    with:
      python-version: "3.9"
  - name: install dependencies
    run: pip install requests
    shell: bash
  - name: checkout repo
    uses: actions/checkout@v3
  - name: Run action
    run: |
      python3 ${{ github.action_path }}/src/scan_file.py
    env:
      INPUT_DIRS: ${{ inputs.DIRS }}
      INPUT_WHITELIST_LINKS: ${{ inputs.WHITELIST_LINKS }}
      INPUT_WHITELIST_FILES: ${{ inputs.WHITELIST_FILES }}
      INPUT_VERBOSE: ${{ inputs.VERBOSE }}
    shell: bash
  - name: Write summary
    if: always()
    run: |
      summary="$(cat tmp.txt)"
      echo "github_step_summary=far" >> $GITHUB_ENV
      echo "STEP_SUMMARY=outbruh" >> $GITHUB_ENV
    shell: bash
