#!/bin/bash

# Script used to automate the standard steps I take
# installing the action into a cloned repo


mkdir -p .github/workflows

touch .github/workflows/linkcheck.yml

cat << END >> .github/workflows/linkcheck.yml
name: Link-check
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run linksafe
        uses: TechWiz-3/linksafe@main
        with: # comma seperated lists
          # use relative paths, if no dirs specified root dir is scanned
          dirs: ".,./src,./src/subdir,./doc/website,./doc/more"
          # set to false by default
          verbose: true
          whitelist_links: "https://xyz.xyz"
          whitelist_files: "./doc/HACKING.md"
END
