name: Test workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run the action
        uses: TechWiz-3/linksafe@main-refactor
        with:
          dirs: ".,test,src/"
          whitelist_files: "test.txt"
          verbose: true
